name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        deno: ["canary", "v2.x"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}

      - name: Spell-check
        if: matrix.deno == 'v2.x'
        uses: crate-ci/typos@master

      - run: deno task check
      - run: deno task test
      - run: deno task check:types
